name: Mon workflow

on:
  push:
    branches:
      - main

jobs:
  checkout:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Afficher le contenu de README.md
      run: cat README.md
