name: "Workflow 3.6" 
on: 
  push: 
jobs: 
  testing_phase: 
    name: "Running test" 
    runs-on: "ubuntu-latest" 
    steps: 
      - uses: actions/checkout@v2 
        with: 
          repository: https://github.com/tldr-pages/tldr-python-client 
          ref: "3.1.0" 
      - uses: actions/setup-python@v2 
        with: 
          python-version: "3.10" 
      - name: "Installing dependencies" 
        run: | 
          pip install -r requirements.txt 
      - name: "Installing pytest and pytest-html" 
        run: | 
          pip install pytest pytest-html 
      - name: "Running tests and generating report" 
        run: | 
          pytest --html=report.html 
      - name: "Uploading report" 
        uses: actions/upload-artifact@v2 
        with: 
          name: Test report 
          path: report.html 
