name: "Workflow 5.3"
on:
  push:
jobs:
  prepare_tests:
    name: "Prepare Tests"
    runs-on: "ubuntu-latest"
    outputs:
      HOST: ${{ steps.setup_host.outputs.HOST }}
      DATABASE: ${{ steps.setup_host.outputs.DATABASE }}
    steps:
      - name: "Setup Host"
        id: setup_host
        run: |
          echo "HOST=srv1" >> ${{ github.workspace }}/output.txt
          echo "DATABASE=prep002" >> ${{ github.workspace }}/output.txt
        shell: bash
  display_infos:
    name: "Display Infos"
    needs: prepare_tests
    runs-on: "ubuntu-latest"
    steps:
      - name: "Print Variables"
        run: |
          echo "HOST: ${{ needs.prepare_tests.outputs.HOST }}"
          echo "DATABASE: ${{ needs.prepare_tests.outputs.DATABASE }}"
