name: Poetry Build Workflow

on:
  push:


jobs:
  poetry_build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Actions
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install Poetry
        run: |
          python -m pip install --upgrade pip
          python -m pip install poetry

      - name: Cache for Poetry
        uses: actions/cache@v3
        with:
          path: ~/.cache/pypoetry
          key: ${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock') }}
          restore-keys: |
            ${{ runner.os }}-poetry-
            ${{ runner.os }}-

      - name: Install dependencies via Poetry
        run: |
          poetry config virtualenvs.create false
          poetry install --no-dev

      - name: Run tests
        run: |
          pip install pytest
          poetry run pytest

      - name: Build distributions
        run: |
          poetry build

      - name: Save distribution artifacts
        uses: actions/upload-artifact@v3
        with:
          name: distributions
          path: dist/
